import type { CockpitNavItem } from "@/types/cockpit";

export const cockpitNavigation: CockpitNavItem[] = [
  {
    id: "cockpit-home",
    href: "/dashboard",
    label: "Accueil cockpit",
    description: "Resume operationnel du jour",
    status: "Operationnel",
    showStatus: true,
  },
  {
    id: "assistant",
    href: "/interface",
    label: "Assistant de L’Édifice",
    description: "Projet, intérieur, équilibre",
    status: "En migration",
    showStatus: true,
  },
  {
    id: "overview",
    href: "/interface/overview",
    label: "Tableau de bord",
    description: "Fondations du cockpit",
    status: "Disponible",
  },
  {
    id: "post-creation",
    href: "/interface/post-creation",
    label: "Atelier de contenu",
    description: "Idées, scripts et formats",
    status: "En migration",
  },
  {
    id: "publishers",
    href: "/interface/publishers",
    label: "Publications",
    description: "Préparer et valider",
    status: "En migration",
  },
  {
    id: "monitoring",
    href: "/interface/monitoring",
    label: "Observatoire",
    description: "Signaux et état",
    status: "Experimental",
    showStatus: true,
  },
  {
    id: "personnel",
    href: "/interface/personnel",
    label: "Espace intérieur",
    description: "Routines et énergie",
    status: "Experimental",
  },
  {
    id: "settings",
    href: "/interface/settings",
    label: "Réglages",
    description: "Compte et connexions",
    status: "A securiser",
    showStatus: true,
  },
  {
    id: "links",
    href: "/interface/resources",
    label: "Ressources",
    description: "Repères et documents",
    status: "Disponible",
    showStatus: true,
  },
];
